apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-ci-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-ci-cd
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: kube-ci-cd
    spec:
      containers:
        - name: kube-ci-cd
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always
          ports:
            -
              containerPort: 8080
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator
              port: 8080
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
            initialDelaySeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 768Mi